### PR TITLE
Maintain proxied status.

### PR DESCRIPTION
**Pull request by mickwall001**

### CODE REVIEW

**Comment by namukcom** [comment]
When "proxied" parameter is ommitted, it doesn't change proxied or not.
I think it's not necessary to include "proxied" parameter.

**Review by namukcom — COMMENTED** [review]
When "proxied" parameter is ommitted, it doesn't change proxied or not.
I think it's not necessary to include "proxied" parameter.

**Comment by mickwall001** [comment]
It changes it for me, without this change all my sites that are proxied are set to DNS only

**Comment by namukcom** [comment]
I should check the CF API again. Thanks.

**Comment by mickwall001** [comment]
Thanks, CF api says its optional but I definitely see all updates changing the status.  All three of my websites went to DNS only today as my IP changed!

Thanks for the script - really useful

**Comment by namukcom** [comment]
I confirmed "proxied issue". Thanks again.

**Review by namukcom — APPROVED** [review]

**Pull request merged**
